# Generated by Django 5.2.8 on 2025-11-17 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notes', '0001_initial'),
        ('relationships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='relationship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='relationships.relationship'),
        ),
    ]
