# Generated by Django 5.2.8 on 2025-11-17 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('VIDEO_CALL', 'Video Call'), ('PHONE_CALL', 'Phone Call'), ('LIVE_CHAT', 'Live Chat'), ('TEXT_MESSAGE', 'Text Message'), ('IN_PERSON', 'In Person'), ('USER_RECORD', 'User Record'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('interaction_date', models.DateTimeField(auto_now_add=True)),
                ('duration_minutes', models.IntegerField(blank=True, help_text='Duration in minutes (if applicable)', null=True)),
                ('transcription', models.TextField(blank=True, help_text='Full transcription of the interaction')),
                ('summary', models.TextField(blank=True, help_text='AI-generated summary of the interaction')),
                ('video_path', models.CharField(blank=True, help_text='Path to stored video file', max_length=500, null=True)),
                ('audio_path', models.CharField(blank=True, help_text='Path to stored audio file', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Interaction',
                'verbose_name_plural': 'Interactions',
                'db_table': 'interactions',
                'ordering': ['-interaction_date'],
            },
        ),
    ]
