# Generated by Django 5.2.8 on 2025-11-17 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interactions', '0001_initial'),
        ('relationships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='relationships',
            field=models.ManyToManyField(help_text='People involved in this interaction', related_name='interactions', to='relationships.relationship'),
        ),
    ]
