# Generated by Django 5.2.8 on 2025-11-17 22:15

import django.db.models.deletion
import pgvector.django
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('relationships', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', pgvector.django.VectorField(dimensions=128, help_text='Face embedding vector (128 dimensions for face_recognition library)')),
                ('image_path', models.CharField(blank=True, help_text='Path to the source image', max_length=500, null=True)),
                ('confidence_score', models.FloatField(default=1.0, help_text='Confidence score of the face detection (0-1)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_signatures', to='relationships.relationship')),
            ],
            options={
                'verbose_name': 'Face Signature',
                'verbose_name_plural': 'Face Signatures',
                'db_table': 'face_signatures',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['relationship'], name='face_signat_relatio_4ddfba_idx')],
            },
        ),
        migrations.CreateModel(
            name='VoiceSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', pgvector.django.VectorField(dimensions=512, help_text='Voice embedding vector (dimensions depend on the model used)')),
                ('audio_path', models.CharField(blank=True, help_text='Path to the source audio sample', max_length=500, null=True)),
                ('confidence_score', models.FloatField(default=1.0, help_text='Confidence score of the voice detection (0-1)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_signatures', to='relationships.relationship')),
            ],
            options={
                'verbose_name': 'Voice Signature',
                'verbose_name_plural': 'Voice Signatures',
                'db_table': 'voice_signatures',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['relationship'], name='voice_signa_relatio_da12ea_idx')],
            },
        ),
    ]
