# Generated by Django 5.2.8 on 2025-11-17 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('relationship_type', models.CharField(choices=[('FAMILY', 'Family'), ('FRIEND', 'Friend'), ('COLLEAGUE', 'Colleague'), ('ACQUAINTANCE', 'Acquaintance'), ('BUSINESS', 'Business Contact'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('notes_summary', models.TextField(blank=True, help_text='Summary of all notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Relationship',
                'verbose_name_plural': 'Relationships',
                'db_table': 'relationships',
                'ordering': ['-updated_at'],
            },
        ),
    ]
